name: Deploy to Github Pages

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build_and_deploy:
    name: Build documentation and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: npm ci --only=dev && npm run document
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
