name: Deploy alpha release to GitHub

on:
  push:
    branches:
      - main
    paths:
      - 'src/*.ts'
      - 'src/messages/*.ts'

jobs:
  build:
    name: Build from source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Store builds
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            package.json
            README.md
            LICENSE
            lib

  alpha-branch:
    name: Deploy alpha
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: alpha

      - name: Clear old build
        run: |
          rm -rf !(".git")

      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Push to alpha
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actor
          message: New alpha release
